### ISSUE TITLE
Webapi context session

### ISSUE THREAD

**Issue by dgonzo** [dgonzo/eventsourcing-kanban#2]
@johnbywater I'm hitting another sticking point with db session within the context of the webapi. The README has the trace for the current error -- sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: integer_sequenced_items

I can confirm that the tables were created with all sqlalchemy bindings I've tried the web framework and eventsourcing's bindings.

I'm using [Apistar](https://github.com/encode/apistar) as the api framework. I know that's not the example in `eventsourcing` but we are using it internally at work so if I can double-dip on learning `eventsourcing` library in the context I'm facing.

**Comment by johnbywater** [comment]
Is it because I changed the DB_HOST to in memory database? Perhaps make sure it's actually using a file system path?

Also, you probably need to think about the scoping of the session. It seems the with Apistar a session is created and passed into the request, so it is "context" managed? As discussed earlier, at the moment at least, a session facade needs to be passed into your eventsourcing Application object when it is constructed, and the actual session is managed behind the facade. So I don't think the sqlalchemy backend is very suitable, because you can't create an eventsourcing Application object for each thread in a multi-threaded application. But if you wanted to use it for configuration, then you could perhaps create a scoped session with something like `scoped_session(backend.Session)`, construct the eventsourcing Application with that facade, and ignore the session passed into the request.

You might also need to declare your event store's active record class using the declarative base from the framework.

**Comment by johnbywater** [comment]
See also http://flask-sqlalchemy-session.readthedocs.io/en/v1.1/

**Comment by johnbywater** [comment]
See also http://docs.sqlalchemy.org/en/latest/orm/contextual.html#using-custom-created-scopes

**Comment by dgonzo** [comment]
Thank you.
